# **[EIE409] Programación 2**

## **Clase 6:**

### **Tabla de contenido**

1. PyTorch.



## **1. PyTorch**

### **1.1 Instalar PyTorch**

Para instalar PyTorch es necesario tener una GPU, luego debes derigirte a la [documentación oficial](https://pytorch.org) y seleccionar el sistema operativo que tienes, si utilizas conda o pip, etc. En mi caso, seleccioné lo que se muestra en la imagen abajo.

![Instalación PyTorch](../assets/torch_1.png)

Verificamos que no tenemos torch

In [1]:
!pip show torch

Instalamos torch utilizando el comando que nos entregó la página de pytorch. Nota, agregué ! y elminé el 3 de pip.

In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
     ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
     ---------------------- ----------------- 3.4/6.2 MB 18.4 MB/s eta 0:00:01
     ---------------------------------------- 6.2/6.2 MB 20.0 MB/s eta 0:00:00
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
   ---------------------------------------- 0.0/2.5 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 GB 29.7 MB/s eta 0:01:26
   ---------------------------------------- 0.0/2.5 GB 34.9 MB/s eta 0:01:13
   ---------------------------------------- 0.0/2.5 GB 37.3 MB/s eta 0:01:08
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.1/2.5 GB 39.9 MB/s eta 0:0

#### **1.1.1 Importar torch**

In [2]:
import torch

#### **1.1.2 Verificar que estamos utilizando la GPU**

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.__version__

'2.6.0+cu124'

In [8]:
!nvidia-smi

Sun Feb 16 20:30:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8             N/A /   30W |       0MiB /   4096MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### **1.2 Introducción a Tensores**

#### **1.2.1 Escalares (Tesnores 0D)**

In [9]:
escalar = torch.tensor(7)

In [ ]:
# Muestra el tensor

In [ ]:
# Podemos mostrar la dimensión del tensor
escalar.ndim

In [ ]:
# Podemos ver el tamaño del tensor
escalar.size()

In [ ]:
# Podemos mostrar el tipo de dato del tensor
escalar.dtype

In [ ]:
# Podemos ver la forma del tensor o la cantidad de elementos
escalar.shape

In [ ]:
# Podemos convertirlo a un entero de python
escalar.item()

#### **1.2.2 Vectores (Tensores 1D)**

In [17]:
vector = [7, 5, 3, 1]

tensor = torch.tensor(vector)

In [ ]:
# Muestra el tensor

In [22]:
# Muestra la dimensión del tensor

In [ ]:
# Muestra el tamaño del tensor

In [ ]:
# Muestra  el tipo de dato del tensor

In [ ]:
# Muestra la forma del tensor o la cantidad de elementos

#### **1.2.3 Matriz (Tensores 2D)**

In [38]:
m = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix = torch.tensor(m)

In [ ]:
# Muestra el tensor, su tamaño, su dimensión, su tipo de dato, su forma.

In [39]:
matrix.ndim

2

#### **1.2.4 Tensores 3D**

In [31]:
v = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]]

tensor = torch.tensor(v)

In [32]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
v2 = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]

tensor = torch.tensor(v2)

In [37]:
tensor.shape

torch.Size([2, 3, 3])

In [40]:
tensor.ndim

3

Podemos ver esto como una secuencia de matrices.

#### **1.2.5 Tensores 4D**

Un ejemplo de tensores en 3D puede ser una secuencia de imágenes (matrices) a color.

In [41]:
v = [[[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]]

tensor = torch.tensor(v)

In [42]:
tensor.ndim

4

In [43]:
tensor.shape

torch.Size([1, 2, 3, 3])

![imagen](../assets/color_image_representation.png)

#### **1.2.6 Tensores Aleatorios (Random Tensor)**

In [ ]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

In [ ]:
random_tensor_2d = torch.rand(3,4) # Recuerda que los argumentos representan la fila y columna del tensor
random_tensor_2d

In [ ]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_3d = torch.rand(3,4,4) 
random_tensor_3d

In [53]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_4d = torch.rand(3,4,4,3) 
random_tensor_4d

tensor([[[[0.1950, 0.5172, 0.1588],
          [0.6392, 0.8143, 0.4945],
          [0.7623, 0.8502, 0.8192],
          [0.0238, 0.9532, 0.6322]],

         [[0.0043, 0.6244, 0.1557],
          [0.9628, 0.8965, 0.1702],
          [0.1294, 0.5352, 0.3675],
          [0.7141, 0.0342, 0.8707]],

         [[0.5448, 0.5098, 0.1811],
          [0.5311, 0.8397, 0.9871],
          [0.1762, 0.2904, 0.6040],
          [0.7812, 0.0803, 0.3134]],

         [[0.1028, 0.9595, 0.3294],
          [0.8007, 0.7726, 0.5461],
          [0.5975, 0.8253, 0.4368],
          [0.7631, 0.4335, 0.5079]]],


        [[[0.6709, 0.0489, 0.2619],
          [0.1009, 0.3480, 0.4686],
          [0.6996, 0.0998, 0.0815],
          [0.8470, 0.4404, 0.2472]],

         [[0.3846, 0.5267, 0.1344],
          [0.0191, 0.1717, 0.8963],
          [0.6450, 0.0023, 0.2307],
          [0.8792, 0.9796, 0.5994]],

         [[0.7780, 0.5824, 0.7910],
          [0.1091, 0.5840, 0.0567],
          [0.0082, 0.9203, 0.5484],
          [0.7

In [55]:
random_tensor_4d.shape

torch.Size([3, 4, 4, 3])

##### **Tensores deterministas**

Podemos replicar los valores obtenidos de un tensor aleatorio

In [ ]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.6153, 0.7756, 0.7026, 0.6364, 0.9205, 0.0077])

In [48]:
torch.manual_seed(5)
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166])

In [50]:
torch.manual_seed(5)
random_tensor_1d = torch.rand(8) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166, 0.1644, 0.7379])

#### **1.2.7 Zeros & Ones**

In [58]:
unos_1d = torch.ones(5)
unos_2d = torch.ones(5, 5)

In [ ]:
# Muestra los tensores

In [60]:
zeros_1d = torch.zeros(5)
zeros_2d = torch.zeros(3,3)

In [ ]:
# Muestra los tensores

#### **1.2.8 Rango de tensores**

##### **linspace()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch-linspace) |

In [66]:
range = torch.linspace(0,10,10)

In [ ]:
# Muestra el tensor generado

##### **arange()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.arange.html) |

In [69]:
range = torch.arange(0,10,1)

In [ ]:
# Muestra el tensor generado

#### **1.2.9 Tensors-like**

In [71]:
tensor = torch.arange(0,10,1, dtype=torch.uint8)

In [73]:
tensor.dtype

torch.uint8

In [75]:
test_tensor = torch.arange(0,10,1)

In [76]:
test_tensor.dtype

torch.int64

In [77]:
ones_tensor = torch.ones_like(tensor)
ones_tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [79]:
test_ones_tensor = torch.ones_like(test_tensor)
test_ones_tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### **1.3.1 Tipo de datos en los tensores (Tensors-dtype)**

Existen distintos tipos de datos, se puede revisar la [documentación](https://pytorch.org/docs/stable/tensors.html) para obtener más información.

In [80]:
float_32_tensor = torch.tensor([5, 4, 3], dtype=torch.float32)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [83]:
float_16_tensor = torch.tensor([5, 4, 3], dtype=torch.float16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [85]:
bifloat16_tensor = torch.tensor([5, 4, 3], dtype=torch.bfloat16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [87]:
int8_tensor = torch.tensor([5, 4, 3], dtype=torch.int8)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

#### **1.3.2 Información de los tensores**

In [89]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape del tensor: {some_tensor.shape}")
print(f"Datatype del tensor: {some_tensor.dtype}")
print(f"Device del tensor: {some_tensor.device}") # will default to CPU

tensor([[0.9354, 0.8343, 0.9632, 0.9153],
        [0.5055, 0.7682, 0.5735, 0.6601],
        [0.5253, 0.7777, 0.3530, 0.4517]])
Shape del tensor: torch.Size([3, 4])
Datatype del tensor: torch.float32
Device del tensor: cpu


In [91]:
some_tensor_gpu = torch.rand(3, 4, device=device)

print(some_tensor)
print(f"Shape del tensor: {some_tensor_gpu.shape}")
print(f"Datatype del tensor: {some_tensor_gpu.dtype}")
print(f"Device del tensor: {some_tensor_gpu.device}") # will default to CPU

tensor([[0.9354, 0.8343, 0.9632, 0.9153],
        [0.5055, 0.7682, 0.5735, 0.6601],
        [0.5253, 0.7777, 0.3530, 0.4517]])
Shape del tensor: torch.Size([3, 4])
Datatype del tensor: torch.float32
Device del tensor: cuda:0


### **1.3 Operando con los Tensores**

#### **1.3.1 Operaciones básicas**

In [92]:
tensor = torch.tensor([1, 2, 3])

In [93]:
suma = tensor + 10
resta = tensor - 1
mul = tensor * 2

In [ ]:
# Muestra el resultado

In [98]:
suma = tensor.add(10)
resta = tensor.sub(1)
mult = tensor.multiply(2)

In [ ]:
# Muestra el resultado

#### **1.3.2 Multiplicación Matricial**

Para empezar debemos recordar la multiplicación matricial.

Dadas dos matrices $A$ y $B$, su producto $ C = A \times B $ es posible si el número de columnas de $ A $ es igual al número de filas de $ B $.  

Si $ A $ es de dimensión $ m \times n $ y $ B $ es de dimensión $ n \times p $, entonces $ C $ tendrá dimensión $ m \times p $.  

Cada elemento $ C_{ij} $ de la matriz resultante se obtiene como la suma del producto de los elementos de la fila $ i $ de $ A $ por los elementos de la columna $ j $ de $ B $:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

Ejemplo:  

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

Multiplicamos filas por columnas:

$$
C = \begin{bmatrix} (1\times5 + 2\times7) & (1\times6 + 2\times8) \\ (3\times5 + 4\times7) & (3\times6 + 4\times8) \end{bmatrix}
$$

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

In [7]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

b = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_a = torch.tensor(a)
matrix_b = torch.tensor(b)

c = matrix_a @ matrix_b

In [ ]:
# Muestra el resultado

Verifiquemos la forma de cada matriz y el resultado.

In [9]:
print("Forma de a:", matrix_a.shape)
print("Forma de b:", matrix_b.shape)
print("Forma de c:", c.shape)

Forma de a: torch.Size([3, 3])
Forma de b: torch.Size([3, 2])
Forma de c: torch.Size([3, 2])


In [10]:
c

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100]])

In [12]:
mul_1 = torch.matmul(matrix_a, matrix_b)

In [13]:
mul_1

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100]])

#### **1.3.3 Producto Punto**

In [15]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([3, 3, 3])

In [ ]:
dot_product_1 = tensor_1 @ tensor_2 
dot_product_2 = torch.dot(tensor_1, tensor_2)
dot_product_3 = torch.matmul(tensor_1, tensor_2)

In [ ]:
# Muestra el resultado

#### **1.3.4 Transpuesta**

In [24]:
tensor_1 = torch.tensor([[1, 2, 3]])
tensor_1

tensor([[1, 2, 3]])

In [ ]:
# Transpuesta utilizando el método 1
transpuesta_m1 = tensor_1.T
transpuesta_m1

tensor([[1],
        [2],
        [3]])

In [27]:
# Transpuesta utilizando el método 2
transpuesta_m2 = torch.transpose(tensor_1, 1, 0)
transpuesta_m2

tensor([[1],
        [2],
        [3]])

In [28]:
tensor_2 = torch.tensor([[1, 2, 3], [5, 5, 5]])
tensor_2

tensor([[1, 2, 3],
        [5, 5, 5]])

In [32]:
tran_1 = torch.transpose(tensor_2, 0, 1)
tran_1

tensor([[1, 5],
        [2, 5],
        [3, 5]])

In [33]:
tran_2 = tensor_2.T
tran_2

tensor([[1, 5],
        [2, 5],
        [3, 5]])

#### **1.3.5 Red Neuronal**

In [34]:
from torch import nn

A continuación, utilizaremos una función lineal que viene integrada en torch, del módulo nn. Se utilizará el método Linear() que creará una matriz de 6x3.

In [37]:
torch.manual_seed(5) # Establecemos una semilla para poder replicar la capa lineal de la red neuronal

linear = nn.Linear(in_features=3, out_features=6, bias=False) # Creamos una capa lineal de 3 entradas y 6 salidas.

In [38]:
linear

Linear(in_features=3, out_features=6, bias=False)

In [39]:
linear.weight

Parameter containing:
tensor([[ 0.3813, -0.4317,  0.4705],
        [ 0.3694,  0.4851, -0.4427],
        [-0.3875,  0.2747, -0.5389],
        [ 0.5706,  0.1229,  0.0746],
        [-0.4937,  0.1840,  0.2483],
        [ 0.0916,  0.5553,  0.1734]], requires_grad=True)

In [45]:
torch.manual_seed(5)
x = torch.rand(3)
x

tensor([0.8303, 0.1261, 0.9075])

In [48]:
y = linear(x)
y

tensor([ 0.6891, -0.0338, -0.7762,  0.5569, -0.1614,  0.3034],
       grad_fn=<SqueezeBackward4>)

Ahora haremos el mismo proceso anterior pero manual. Pero debemos recordar la forma que deben tener estas matrices para poder ser multiplicadas. 

x -> (3,)\
pesos -> (6, 3)

Para poder realizar la multiplicación matricial, la ``columna de la matriz A debe ser igual a la fila de la matriz B``.

In [ ]:
pesos = linear.weight

result = torch.matmul(pesos, x)

In [ ]:
# Muestra el resultado

#### **1.3.6 min, max, mean, sum**

In [55]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# Obtener el mínimo del tensor
x.min()

tensor(0)

In [57]:
# Obtener el máximo del tensor
x.max()

tensor(90)

In [58]:
# Obtener la media del tensor
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [59]:
# Obtener la media del tensor
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Obtener la suma
x.sum()

tensor(450)

In [61]:
# Obtener la suma
sum(x)

tensor(450)

#### **1.3.7 Positional min/max (Obtener índice del tensor)**

In [62]:
x = torch.arange(10, 110, 10)
x

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [64]:
print(f"Tensor: {x}")
print(f"Índice del valor máximo del tensor: {x.argmax()}")
print(f"Índice del valor mínimo del tensor: {x.argmin()}")

Tensor: tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Índice del valor máximo del tensor: 9
Índice del valor mínimo del tensor: 0


#### **1.3.8 Cambiar el tipo de dato**

In [65]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [66]:
f16 = tensor.type(torch.float16)
f16.dtype

torch.float16

In [70]:
tensor_2 = torch.tensor([1, 255, 256, 257])
tensor_2.dtype

torch.int64

In [71]:
tensor_u8 = tensor_2.type(torch.uint8)

In [72]:
tensor_u8

tensor([  1, 255,   0,   1], dtype=torch.uint8)

### **1.4 Operaciones Avanzadas**