# **[EIE409] Programación 2**

## **Clase 5:**

### **Tabla de contenido**

1. Numpy.



## **1. NumPy**

NumPy (Numerical Python) es una biblioteca fundamental para la computación científica en Python. Proporciona soporte para matrices y arrays multidimensionales, además de funciones matemáticas de alto rendimiento.

A continuación, te dejo la página oficial:

* https://numpy.org/doc/2.2/

[¿Qué es un Array?](https://numpy.org/doc/2.2/user/absolute_beginners.html#what-is-an-array)

### **1.1 Instalar NumPy**

Instalar la dependencia se ejecuta una única vez en tú ambiente. En Google Colab ya viene instalado NumPy, pero en tu dispositivo no. 

In [2]:
!pip install -q numpy

### **1.2 Importar NumPy**

In [1]:
import numpy as np

### **1.3 Creación de Arrays (Arreglos)**

In [2]:
number_list = list(range(1, 11)) # Creamos una lista de números
number_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
array = np.array(number_list)

In [ ]:
# Muestra tu arreglo

In [ ]:
# Podemos crear únicamente un array de ceros
array_ceros = np.zeros((3))

In [ ]:
# Muestra tu arreglo

In [9]:
# Podemos crear únicamente un array de unos 
array_ceros = np.ones((7))

In [ ]:
# Muestra tu arreglo de unos

In [11]:
# Podemos crear un array con una secuencia de valores
arr_range = np.arange(0, 10, 2)

In [ ]:
# Muestra tu secuencia de numeros

In [19]:
# Podemos crear un array con una secuencia de valores
arr_range = np.arange(0, 1, 0.1)

In [ ]:
# Muestra tu secuencia de numerps

In [ ]:
# Podemos crear un arreglo con valores equidistantes
arr_linspace = np.linspace(0, 10, 5)

In [ ]:
# Muestra tu arreglo de numeros

#### **Diferencia entre `arange()` y `linspace()`**

La diferencia principal entre `np.arange()` y `np.linspace()` radica en la forma en que generan los valores:

1. **`np.arange(start, stop, step)`**  
   - Genera valores en un rango con un **paso constante** entre ellos.
   - No necesariamente incluye el valor de `stop` si no coincide con el paso exacto.
   - Es similar a `range()` en Python, pero funciona con arrays de NumPy.
   - Ejemplo:
     ```python
     import numpy as np
     arr = np.arange(0, 10, 2)
     print(arr)  # Output: [0 2 4 6 8]
     ```

2. **`np.linspace(start, stop, num)`**  
   - Genera un número `num` de valores equidistantes entre `start` y `stop`.
   - SIEMPRE incluye el valor de `stop`.
   - Se usa cuando quieres un número específico de puntos en un intervalo.
   - Ejemplo:
     ```python
     arr = np.linspace(0, 10, 5)
     print(arr)  # Output: [ 0.   2.5  5.   7.5 10. ]
     ```

#### Resumen:
- **`arange()`**: Define valores con un paso fijo.
- **`linspace()`**: Define valores con un número fijo de puntos entre dos límites.

¿Cuál usar?  
- Usa `arange()` si sabes el **paso exacto** que quieres.  
- Usa `linspace()` si sabes **cuántos puntos** necesitas. 

### **1.4 Creación de matrices**

In [32]:
lista = list(range(1, 4)) # Creamos una lista de números
matriz = np.array([lista, lista, lista])

In [ ]:
# Muestra tu matriz

### **1.5 Atributos de NumPy**

Recordemos que en Python todo es un objeto, dado eso tenemos objetos que tienen métodos y atributos. En NumPy existen atributos importantes, como:

* Saber la dimensión del arreglo o matriz.
* El número de dimensiones.
* Cantidad total de elementos.
* El tipo de dato de los elementos.

In [24]:
array = np.linspace(1, 10, 10)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# Saber la dimensión o forma
array.shape

(10,)

In [ ]:
# Saber el número de dimensiones
array.ndim

1

In [27]:
# SAber la cantidad de elementos
array.size

10

In [28]:
# Saber el tipo de dato de los elementos
array.dtype

dtype('float64')

### **1.6 Operaciones Matemáticas**

Revisar más operaciones

#### **1.6.1 Suma (Punto a punto)**

In [2]:
# 1º: Podemos sumar ndarrays

vector1 = np.ones(5)
vector2 = np.ones(5)

In [ ]:
# Mostrar los vectores por pantalla

In [5]:
suma = vector1 + vector1 
suma

array([2., 2., 2., 2., 2.])

In [6]:
# 2º: Podemos sumar un ndarray con cualquier tipo de dato, int, float, de python.

vector1 = np.ones(5)
escalar = 6 

In [7]:
suma = vector1 + escalar 
suma

array([7., 7., 7., 7., 7.])

In [12]:
# Otro ejemplo, 
suma = np.ones(4) + 25.987 
suma

array([26.987, 26.987, 26.987, 26.987])

In [17]:
# 3º: Podemos sumar matrices punto a punto

matriz1 = np.ones((3,3))
matriz2 = np.ones((3,3))

In [19]:
suma_punto_punto = matriz1 + matriz2 
suma_punto_punto

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [21]:
# 4º: Podemos sumar matrices punto a punto pero con un escalar

matriz1 = np.ones((3,3))
escalar = 25

suma = matriz1 + escalar
suma

array([[26., 26., 26.],
       [26., 26., 26.],
       [26., 26., 26.]])

#### **1.6.2 Resta (Punto a punto)**

De igual manera que lo hicimos anteriormente, podemos realizar la resta de vectores, matrices, etc.

In [23]:
vector1 = np.ones(4)
vector2 = np.ones(4)

In [ ]:
# Muestra el resultado de los dos vectores

In [25]:
resta = vector1 - vector2

In [ ]:
# Muestra el resultado de los dos vectores

In [28]:
vector1 = np.ones(5) + 25 
escalar = 5

resta = vector1 - escalar 

In [ ]:
# ¿Qué resultado debería dar?

#### **1.6.3 Multiplicación (Punto a punto)**

In [29]:
vector1 = np.ones(4) + 1
vector2 = np.ones(4) + 1

mult = vector1 * vector2 

In [ ]:
# Muestra el resultado

In [ ]:
vector = (np.ones(4) + 1) * 5

In [ ]:
# ¿Qué debería obtener?

In [33]:
matriz1 = np.ones((2,2))
matriz2 = np.zeros((2,2))

In [35]:
mult = matriz1 * matriz2 

In [ ]:
# ¿Qué debería obtener?

In [36]:
matriz = (np.ones((2,2)) + 1) * 3

In [ ]:
# ¿Qué debería obtener?

#### **1.6.4 División (Punto a punto)**

In [41]:
vector1 = np.ones(4) + 1
vector2 = np.ones(4)

div = vector1 / vector2 
div

array([2., 2., 2., 2.])

In [42]:
vector = np.ones(5) / 2 
vector

array([0.5, 0.5, 0.5, 0.5, 0.5])

#### **1.6.5 Suma Total**

In [ ]:
suma_1d = np.sum(np.ones(7))
suma_1d

np.float64(7.0)

In [45]:
suma_2d = np.sum(np.ones((2,2)))
suma_2d

np.float64(4.0)

Veamos otro ejemplo con números aleatorios.

In [49]:
np.random.seed(5)

matriz = np.random.random((2,2))
matriz

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091]])

In [47]:
np.sum(matriz)

np.float64(2.2180555405444635)

Verifiquemos el resultado obtenido...

In [48]:
result = 0.22199317 + 0.87073231 + 0.20671916 + 0.91861091
result

2.21805555

Por lo tanto, podemos ahorrarnos el uso de tener que recorrer el array y sumar dentro de dos for, ¿Cómo?

In [51]:
sum = 0

for i in range(len(matriz[:])):
    for j in range(len(matriz[0, :])):
        sum = sum + matriz[i,j]

sum 

np.float64(2.2180555405444635)

Supongamos que tenemos una matriz de 4x4.

In [55]:
np.random.seed(5)

matriz = np.random.random((4,4))
matriz

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091],
       [0.48841119, 0.61174386, 0.76590786, 0.51841799],
       [0.2968005 , 0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703, 0.27408646]])

In [57]:
sum = 0

for i in range(len(matriz[:])):
    for j in range(len(matriz[0, :])):
        sum = sum + matriz[i,j]

print("Suma al utilizar numpy: ", np.sum(matriz))
print("Suma al utilizar el for: ", sum)

Suma al utilizar numpy:  7.659882315598623
Suma al utilizar el for:  7.659882315598622


### **1.7 Slicing en NumPy**

En esta sección vamos a ver cómo acceder a un o conjuntos de elementos, modificación de elementos, etc.

#### **1.7.1 Array**

In [3]:
np.random.seed(5)

vector = np.random.random(5)
vector

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [ ]:
# Mostrar primer elemento
vector[0]

np.float64(0.22199317108973948)

In [5]:
# Mostrar segundo elemento
vector[1]

np.float64(0.8707323061773764)

In [7]:
# Mostrar último elemento
vector[4]

np.float64(0.48841118879482914)

In [ ]:
# Mostrar último elemento
vector[-1]

In [8]:
# Mostrar último elemento
vector[len(vector)-1]

np.float64(0.48841118879482914)

**Podemos cambiar los elementos**

In [9]:
# Cambiando el primer elemento por un número entero
vector[0] = 25
vector

array([25.        ,  0.87073231,  0.20671916,  0.91861091,  0.48841119])

**Slicing permite cambiar un conjunto de elementos**

In [10]:
vector[1:3] = -4
vector

array([25.        , -4.        , -4.        ,  0.91861091,  0.48841119])

**Puedo mostrar los datos cambiados**

In [11]:
vector[0:3]

array([25., -4., -4.])

#### **1.7.2 Matriz**

In [12]:
np.random.seed(5)

matriz = np.random.random((5,5))
matriz

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [13]:
# Mostrar el primer elemento
matriz[0]

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

Al utilizar los corchetes e indicar "el primer elemento", nos retorna la primera fila. Para acceder al primer elemento se debe hacer lo siguiente:

$$
\text{matriz}[fila, columna]
$$

In [15]:
# Mostrar el primer elemento
matriz[0,0]

np.float64(0.22199317108973948)

In [ ]:
# Otra forma de acceder utilizando otra notación
matriz[0][0]

np.float64(0.22199317108973948)

In [18]:
# Podemos acceder al segundo elemento de la primera fila
matriz[0,1]

np.float64(0.8707323061773764)

In [19]:
# Podemos acceder a la segunda fila y seleccionar tres elementos
matriz[2,0:3]

array([0.08074127, 0.7384403 , 0.44130922])

In [20]:
# Podemos acceder a la última columna
matriz[:,-1]

array([0.48841119, 0.18772123, 0.87993703, 0.57983781, 0.32756395])

**Podemos cambiar el valor**

In [24]:
# Cambiar toda la primera fila por unos
matriz[0] = 1
matriz

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [26]:
# Cambiar la última columna por cero
matriz[:,-1] = 0
matriz

array([[1.        , 1.        , 1.        , 1.        , 0.        ],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.        ],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.        ],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.        ],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.        ]])

In [28]:
# Cambiar el valor del centro
matriz[2,2] = 55
matriz

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.61174386,  0.76590786,  0.51841799,  0.2968005 ,  0.        ],
       [ 0.08074127,  0.7384403 , 55.        ,  0.15830987,  0.        ],
       [ 0.27408646,  0.41423502,  0.29607993,  0.62878791,  0.        ],
       [ 0.5999292 ,  0.26581912,  0.28468588,  0.25358821,  0.        ]])

### **1.8 Cambiar la forma del Array**

| [Información de referencia](https://numpy.org/doc/2.2/reference/routines.array-manipulation.html#changing-array-shape) |

#### **1.8.1 Reshape**

In [3]:
matriz_original = np.ones((2,4))
matriz_original

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
matriz_original.reshape((4,2)) # Podemos invertir las dimensiones, sin afectar el objeto instanciado

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
matriz_original.reshape((8,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

#### **1.8.2 Flatten**

In [8]:
matriz_original = np.ones((2,4))
matriz_original

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
matriz_original.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1.])

### **1.9 Operaciones de Transpuesta**

| [Información de referencia](https://numpy.org/doc/2.2/reference/routines.array-manipulation.html#transpose-like-operations) |

In [12]:
vector = np.arange(1,10)
vector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
vector.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.seed(5)

# Le estoy diciendo que genere valores enteros del 0 al 10 y que tenga tamaño 2x4
matriz = np.random.randint(0,10,(2,4))
matriz

array([[3, 6, 6, 0],
       [9, 8, 4, 7]], dtype=int32)

In [23]:
matriz.shape

(2, 4)

In [24]:
matriz_transpuesta = matriz.T
matriz_transpuesta

array([[3, 9],
       [6, 8],
       [6, 4],
       [0, 7]], dtype=int32)

In [25]:
matriz_transpuesta.shape

(4, 2)

### **2.1 Broadcasting en NumPy**

El **broadcasting** permite realizar operaciones aritméticas entre arrays de diferentes formas sin necesidad de replicar datos. NumPy expande automáticamente las dimensiones cuando es posible.

**Reglas de Broadcasting**

* Si las dimensiones no coinciden, NumPy añade dimensiones de tamaño 1 a la izquierda.
* Si una dimensión es 1, se expande para que coincida con la otra.
* Si las dimensiones no son compatibles, NumPy genera un error.

Anteriormente vimos la **suma punto a punto** que es una operación de broadcasting, ahora lo haremos cuando tenemos matrices con distintas dimensiones.

In [31]:
np.random.seed(5)

A = np.random.randint(0,10,(2,3))
A

array([[3, 6, 6],
       [0, 9, 8]], dtype=int32)

In [29]:
A.shape

(2, 3)

In [34]:
np.random.seed(5)

B = np.random.randint(0,10,(2,1))
B

array([[3],
       [6]], dtype=int32)

In [35]:
B.shape

(2, 1)

In [ ]:
suma = A + B # Ocurre que B se suma a cada fila de A
suma

array([[ 6,  9,  9],
       [ 6, 15, 14]], dtype=int32)

### **2.2 Squeeze en NumPy**

El método **squeeze()** elimina dimensiones de tamaño 1 de un array.

In [37]:
A = np.array([[[1,2,3]]])
A

array([[[1, 2, 3]]])

In [38]:
A.shape

(1, 1, 3)

In [41]:
B = A.squeeze()

In [42]:
B

array([1, 2, 3])

In [43]:
B.shape

(3,)

### **2.3 Concatenación en NumPy**

**concatenate** une arrays existentes a lo largo de un eje existente, sin agregar nuevas dimensiones.

In [44]:
A = np.array([[1, 2, 3], [4, 5, 6]]) 
B = np.array([[7, 8, 9], [10, 11, 12]])  

In [ ]:
# Muestre los arrays

* **axis=0**: Une verticalmente
* **axis=1**: Une horizontalmente

In [45]:
C = np.concatenate((A, B), axis=0)  # Une en filas (verticalmente)
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
C = np.concatenate((A, B), axis=1)
C

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### **2.4 Stack en NumPy**

**stack** apila arrays creando una nueva dimensión, lo que aumenta el número de ejes en el resultado.

In [52]:
np.random.seed(5)

vector1 = np.arange(0,3,1)
vector2 = np.random.randint(0,4,(3))

In [58]:
stack = np.stack((vector1, vector2), axis=-1)
stack

array([[0, 3],
       [1, 2],
       [2, 3]])

##### **Diferencias Clave**
| Función       | ¿Crea nueva dimensión? | Modifica la forma del array | Ejemplo típico |
|--------------|----------------------|----------------------------|----------------|
| `concatenate` | ❌ No                 | Une sobre un eje existente | Juntar matrices en filas o columnas |
| `stack`       | ✅ Sí                 | Agrega un nuevo eje        | Crear un tensor 3D o mayor |

### **2.5 Flips en NumPy**

In [61]:
np.random.seed(5)

matriz = np.random.randint(0,255,(3,3))
matriz

array([[ 99, 206, 239],
       [189, 230, 118],
       [144,  73,   8]], dtype=int32)

In [62]:
flip_1 = np.flip(matriz, 0)
flip_1

array([[144,  73,   8],
       [189, 230, 118],
       [ 99, 206, 239]], dtype=int32)

In [63]:
flip_2 = np.flip(matriz, 1)
flip_2

array([[239, 206,  99],
       [118, 230, 189],
       [  8,  73, 144]], dtype=int32)

### **2.6 Reshape en NumPy**

In [64]:
vector = np.arange(8)
vector

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
# Ahora convertiremos el vector a una matriz
matriz = vector.reshape(2,4)

In [68]:
# Muestra el contenido de la matriz

## **2. Ejercicios**

## **Resumen NumPy**

### **Atributos Importantes**

* array.shape -> tuple: (Saber la dimensión o forma, retorna una tupla)
* array.ndim -> int (retorna el número de dimensiones)
* array.size -> int (retorna la cantidad de elementos)
* array.dtype -> obj (Retorna un objeto que muestra el tipo de dato)