# **1. Clase Ejercicios Prueba 2**

## **1.1 NumPy**

1. Crear un tensor 1D con 9 elementos.
2. Mostrar el tipo de datos del tensor creado.
3. Crear un tensor 2D de tamaño 25x25 con datos aleatorios.
4. Mostrar la forma del tensor creado.
5. Crear un tensor 1D con 30 números unos.
6. Del tensor creado anteriormente, convertirlo de 1D a 2D y que sea de la forma 3x10.
7. Crear un tensor que tenga 20 elementos y que estén entre 0 y 1.
8. Suma dos tensores 1D de tamaño 5 con valores aleatorios manteniendo la misma semilla.
9. Encuentra el promedio y desviación estándar de un tensor 1D con 20 elementos aleatorios (utiliza semilla).
10. Crea un tensor 2D de tamaño 50x50 con valores aleatorios que estén entre 0 y 255, utilizando semilla=3. Luego, recorre la matriz contando cuántas veces aparece el valor 0.

In [63]:
np.random.seed(3)

tensor_2d = np.random.randint(0, 255, (50,50))
tensor_2d

array([[106, 152, 249, ..., 171,  33, 123],
       [ 79, 176,  37, ..., 223, 141, 165],
       [158,  48, 189, ...,  19, 144, 120],
       ...,
       [ 89, 147, 241, ..., 174,  42, 157],
       [122,  46, 226, ..., 121, 158, 221],
       [214,  73, 225, ...,  56, 135, 126]], dtype=int32)

In [66]:
tensor_2d.shape

(50, 50)

In [67]:
size_row, size_column = tensor_2d.shape

In [68]:
size_row

50

In [74]:
for i in range(size_row):
    for j in range(size_column):
        contenido = tensor_2d[i,j]
        print(contenido)

106
152
249
131
184
200
0
21
253
147
202
107
249
169
138
149
119
166
224
148
172
93
167
142
248
26
81
218
150
66
2
191
60
129
179
90
69
104
110
97
157
106
152
251
62
7
248
171
33
123
79
176
37
20
94
49
149
127
206
244
28
119
54
0
192
233
18
116
191
165
184
184
199
165
253
174
33
113
1
85
117
119
202
235
124
228
99
219
144
80
160
144
242
18
75
183
96
223
141
165
158
48
189
33
52
241
252
242
2
156
36
90
232
172
176
59
202
182
240
228
91
241
21
113
56
104
39
29
160
176
9
33
239
247
188
216
55
11
212
138
112
208
76
68
44
44
251
19
144
120
226
167
178
193
35
173
242
52
1
18
191
2
215
227
148
62
209
22
220
235
135
185
225
171
32
252
92
60
144
27
53
107
8
20
8
152
206
76
19
100
137
26
178
60
133
212
247
95
233
106
81
9
32
141
254
44
71
92
36
125
170
200
252
26
152
148
62
172
158
145
116
32
181
86
39
60
95
32
215
88
161
124
85
51
90
207
92
11
246
233
252
17
179
71
13
95
196
222
63
41
13
205
96
216
60
175
164
183
234
184
213
198
87
220
12
156
111
110
138
139
35
213
220
49
72
217
34
11
89
248
21

In [1]:
import numpy as np

In [16]:
tensor_1d = np.arange(0,9)
# tensor_1d

In [3]:
tensor_1d.dtype

dtype('int64')

In [15]:
tensor_2d = np.random.randint(0,255, (25,25))
# tensor_2d

In [14]:
ones_array = np.ones(30)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
array_convertido = ones_array.reshape((3,10))
array_convertido

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
tensor_1d = np.linspace(0,1,20)
len(tensor_1d)

20

In [49]:
np.random.seed(5)

aleatorio_1 = np.random.randint(0,10,(5))
print(aleatorio_1)
aleatorio_2 = np.random.randint(0,10,(5))
print(aleatorio_2)

[3 6 6 0 9]
[8 4 7 0 0]


In [50]:
suma = aleatorio_1 + aleatorio_2
suma

array([11, 10, 13,  0,  9], dtype=int32)

In [51]:
np.random.seed(5)

tensor = np.random.randint(0,10,(20))
tensor

array([3, 6, 6, 0, 9, 8, 4, 7, 0, 0, 7, 1, 5, 7, 0, 1, 4, 6, 2, 9],
      dtype=int32)

In [52]:
promedio = sum(tensor) / len(tensor)
promedio

np.float64(4.25)

In [55]:
desviacion_estandar = np.sqrt(sum((tensor - promedio) ** 2) / len(tensor))
desviacion_estandar

np.float64(3.096368841078207)

In [ ]:
desviacion_estandar = np.sqrt()

## **1.2 PyTorch**

Haz los mismos ejercicios anteriores utilizando PyTorch.

## **1.3 Matplotlib**

1. Grafica una línea de puntos (x vs y) donde x = [1,2,3], y = [4,5,1].
2. Muestra una gráfica con título, etiquetas de eje X y Y.
3. Dibuja un histograma de valores aleatorios.
4. Grafica dos líneas en la misma figura.
5. Cambia el color y estilo de una línea.
6. Utilizando NumPy o Pytorch muesta una matriz de 500x500 datos aleatorios entre 0 y 255 utilizando imshow y cmap='gray'.
7. Haz el mismo ejercicio anterior pero utilizando subplot, donde la primera imagen los valores están entre 0 y 255, y la segunda imagen los valores están entre 0 y 1. (Utiliza la misma semilla).
8. Gráfica una función matemática como sen(x) o cos(x). Esta funciones matemáticas deben estar dentro de una función que al ejecutarse, le pregunta al usuario si quiere una señal sin(x) o cos(x), también le pregunta al usuario cuántos periodos quiere ver, qué color quiere para la gráfica.

## **1.4 PIL**

1. Abre una imagen y muestra su tamaño.
2. Guarda una imagen con otro formato (por ejemplo, de PNG a JPG).
3. Recorta una región de una imagen.
4. Cambia el brillo de una imagen.
5. Convierte una imagen a escala de grises.
6. Crea una matriz de 500x500 utilizando PyTorch con valores aleatorios entre 0 y 1, averiguar si se puede mostrar con PIL y luego guardar esa imagen creada.

## **1.5 Pandas**

1. Construir un DataFrame a partir de un diccionario que contiene clave (columnas) y los valores son listas de python. Debe contener dos columnas, una llamada nombre y la otra apellido. Los valores de esas columnas serán dos filas con nombres y apellidos aleatorios (elegidos por usted).
2. Muestre el dataframe creado utilizando head().
3. Construya un dataframe que contenga 3 columnas con el nombre de **Parámetro 1**, **Parámetro 2** y **Parámetro 3**. El contenido de estos parámetros será una lista de 50 valores aleatorios que van desde el 0 al 100, puede utilizar NumPy para construir los valores. 
4. Muestre los datos creados y utilice, **.columns**, **.describe()** para mostrar características dataframe.
5. Guarde el dataframe creado como un excel y csv.
6. Cargue el dataframe **dataset.csv** del github: https://github.com/GbrlOl/programacion-2.
7. Muestre sus contenidos.
8. Seleccione únicamente una columna, muestre su primer contenido y su último contenido del dataframe.