## **Tabla de contenido**

1. PyTorch.

## **1. PyTorch**

### **1.1 Instalar PyTorch**

Para instalar PyTorch es necesario tener una GPU, luego debes derigirte a la [documentación oficial](https://pytorch.org) y seleccionar el sistema operativo que tienes, si utilizas conda o pip, etc. En mi caso, seleccioné lo que se muestra en la imagen abajo.

**Nota**: PyTorch también se puede programar en C++ utilizando el módulo llamado Torchlib.

![Instalación PyTorch](../assets/torch_1.png)

Verificamos que no tenemos torch

In [1]:
!pip show torch

Instalamos torch utilizando el comando que nos entregó la página de pytorch. Nota, agregué ! y elminé el número 3 de pip. 

**Importante**: El signo ! únicamente se utiliza en un notebook cuando tenemos celdas de código y queremos ejecutar un comando de consola.

In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
     ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
     ---------------------- ----------------- 3.4/6.2 MB 18.4 MB/s eta 0:00:01
     ---------------------------------------- 6.2/6.2 MB 20.0 MB/s eta 0:00:00
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
   ---------------------------------------- 0.0/2.5 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 GB 29.7 MB/s eta 0:01:26
   ---------------------------------------- 0.0/2.5 GB 34.9 MB/s eta 0:01:13
   ---------------------------------------- 0.0/2.5 GB 37.3 MB/s eta 0:01:08
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.1/2.5 GB 39.9 MB/s eta 0:0

In [1]:
# !pip show torch

#### **1.1.1 Importar torch**

In [2]:
import torch

#### **1.1.2 Verificar que estamos utilizando la GPU**

##### **Para tarjetas con NVIDIA**

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
# device

##### **Para Mac**

In [ ]:
print(torch.backends.mps.is_available())
print(torch.backends.mps.is_built())

In [ ]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

print(device)

In [ ]:
torch.__version__

In [6]:
# !nvidia-smi

### **1.2 Introducción a Tensores**

Cuando trabajamos con el framework PyTorch, utilizamos **tensores**. El tensor hace referencia a un escalar, vector, matriz, etc, dependiendo de su dimensión. Por otro lado, cuando estamos programando es importante aprender los **atributos** más relevantes de los tensores, como:

1. ``tensor.ndim``
2. ``tensor.dtype``
3. ``tensor.shape``
4. ``tensor.device``

Por último, aprender algunos métodos:

1. ``tensor.size()``
2. ``tensor.item()`` (Funciona únicamente con un escalar o tensor 0D)


#### **1.2.1 Escalares (Tensores 0D)**

In [41]:
escalar = torch.tensor(7.7)
# escalar

In [6]:
# Podemos mostrar la dimensión del tensor
# escalar.ndim

In [6]:
# Podemos ver el tamaño del tensor
# escalar.size()

In [7]:
# Podemos mostrar el tipo de dato del tensor
# escalar.dtype

In [8]:
# Podemos ver la forma del tensor o la cantidad de elementos
# escalar.shape

In [ ]:
# Podemos convertirlo a un entero de python
escalar.item()

#### **1.2.2 Vectores (Tensores 1D)**

In [8]:
vector = [7, 5, 3, 1]

tensor = torch.tensor(vector)

In [11]:
# tensor

In [ ]:
# Muestra el tensor

In [12]:
# Muestra la dimensión del tensor
# tensor.ndim

In [13]:
# Muestra el tamaño del tensor
# tensor.size()

In [14]:
# Muestra  el tipo de dato del tensor
# tensor.dtype

In [15]:
# Muestra la forma del tensor o la cantidad de elementos
# tensor.shape

#### **1.2.3 Matriz (Tensores 2D)**

In [51]:
m = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix = torch.tensor(m)

In [56]:
matrix.size()

torch.Size([3, 3])

In [ ]:
# Muestra el tensor, su tamaño, su dimensión, su tipo de dato, su forma.

#### **1.2.4 Tensores 3D**

In [31]:
v = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]]

tensor = torch.tensor(v)

In [16]:
# tensor

In [17]:
# tensor.shape

In [ ]:
v2 = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]

tensor = torch.tensor(v2)

In [18]:
# tensor.shape

In [19]:
# tensor.ndim

Podemos ver esto como una secuencia de matrices.

#### **1.2.5 Tensores 4D**

Un ejemplo de tensores en 3D puede ser una secuencia de imágenes (matrices) a color.

In [41]:
v = [[[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]]

tensor = torch.tensor(v)

In [20]:
# tensor.ndim

In [21]:
# tensor.shape

![imagen](../../assets/color_image_representation.png)

**¿Qué más podemos hacer con los tensores?**

#### **1.2.6 Tensores Aleatorios (Random Tensor)**

In [18]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
# random_tensor_1d

In [20]:
random_tensor_2d = torch.rand(3,4) # Recuerda que los argumentos representan la fila y columna del tensor
# random_tensor_2d

In [22]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_3d = torch.rand(3,4,4) 
# random_tensor_3d

In [23]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_4d = torch.rand(3,4,4,3) 
# random_tensor_4d

In [22]:
# random_tensor_4d.shape

##### **Tensores deterministas**

Podemos replicar los valores obtenidos de un tensor aleatorio

In [31]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.3581, 0.5651, 0.3963, 0.1969, 0.3205, 0.8569])

In [34]:
torch.manual_seed(5)

random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166])

In [50]:
torch.manual_seed(5)
random_tensor_1d = torch.rand(8) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166, 0.1644, 0.7379])

#### **1.2.7 Zeros & Ones**

In [47]:
unos_1d = torch.ones(5)
unos_2d = torch.ones(5, 5)

In [50]:
# Muestra los tensores

In [51]:
zeros_1d = torch.zeros(5)
zeros_2d = torch.zeros(3,3)

In [54]:
# Muestra los tensores

#### **1.2.8 Rango de tensores**

##### **linspace()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch-linspace) |

In [66]:
range = torch.linspace(0,10,10)

In [ ]:
# Muestra el tensor generado

##### **arange()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.arange.html) |

In [55]:
range = torch.arange(0,10,1)

In [ ]:
# Muestra el tensor generado

#### **1.2.9 Tensors-like**

In [71]:
tensor = torch.arange(0,10,1, dtype=torch.uint8)

In [23]:
# tensor.dtype

In [75]:
test_tensor = torch.arange(0,10,1)

In [24]:
# test_tensor.dtype

In [25]:
ones_tensor = torch.ones_like(tensor)
# ones_tensor

In [ ]:
test_ones_tensor = torch.ones_like(test_tensor)
# test_ones_tensor

#### **1.3.1 Tipo de datos en los tensores (Tensors-dtype)**

Existen distintos tipos de datos, se puede revisar la [documentación](https://pytorch.org/docs/stable/tensors.html) para obtener más información.

In [80]:
float_32_tensor = torch.tensor([5, 4, 3], dtype=torch.float32)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [83]:
float_16_tensor = torch.tensor([5, 4, 3], dtype=torch.float16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [85]:
bifloat16_tensor = torch.tensor([5, 4, 3], dtype=torch.bfloat16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [87]:
int8_tensor = torch.tensor([5, 4, 3], dtype=torch.int8)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

#### **1.3.2 Información de los tensores**

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape del tensor: {some_tensor.shape}")
print(f"Datatype del tensor: {some_tensor.dtype}")
print(f"Device del tensor: {some_tensor.device}") # will default to CPU

In [ ]:
device

In [ ]:
some_tensor_gpu = torch.rand(3, 4, device=device)

print(some_tensor)
print(f"Shape del tensor: {some_tensor_gpu.shape}")
print(f"Datatype del tensor: {some_tensor_gpu.dtype}")
print(f"Device del tensor: {some_tensor_gpu.device}") # will default to CPU

### **1.3 Operando con los Tensores**

#### **1.3.1 Operaciones básicas**

Las operaciones suma, resta, multiplicación se hacen elemento a elementos.

In [3]:
tensor = torch.tensor([1, 2, 3])

In [4]:
suma = tensor + 10
resta = tensor - 1
mul = tensor * 2

In [ ]:
# Muestra el resultado

In [98]:
suma = tensor.add(10)
resta = tensor.sub(1)
mult = tensor.multiply(2)

In [ ]:
# Muestra el resultado

#### **1.3.2 Multiplicación Matricial**

Para empezar debemos recordar la multiplicación matricial.

Dadas dos matrices $A$ y $B$, su producto $ C = A \times B $ es posible si el número de columnas de $ A $ es igual al número de filas de $ B $.  

Si $ A $ es de dimensión $ m \times n $ y $ B $ es de dimensión $ n \times p $, entonces $ C $ tendrá dimensión $ m \times p $.  

Cada elemento $ C_{ij} $ de la matriz resultante se obtiene como la suma del producto de los elementos de la fila $ i $ de $ A $ por los elementos de la columna $ j $ de $ B $:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

Ejemplo:  

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

Multiplicamos filas por columnas:

$$
C = \begin{bmatrix} (1\times5 + 2\times7) & (1\times6 + 2\times8) \\ (3\times5 + 4\times7) & (3\times6 + 4\times8) \end{bmatrix}
$$

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

In [35]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

b = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_a = torch.tensor(a)
matrix_b = torch.tensor(b)

c = matrix_a @ matrix_b

Esta operación matricial se está realizando en la CPU.

In [36]:
# c.device

In [ ]:
matrix_a.shape

In [ ]:
matrix_b.shape

In [ ]:
# Muestra el resultado

Verifiquemos la forma de cada matriz y el resultado.

In [ ]:
print("Forma de a:", matrix_a.shape)
print("Forma de b:", matrix_b.shape)
print("Forma de c:", c.shape)

In [12]:
mul_1 = torch.matmul(matrix_a, matrix_b)

In [ ]:
mul_1

#### **1.3.3 Producto Punto**

In [3]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([3, 3, 3])

In [ ]:
dot_product_1 = tensor_1 @ tensor_2 
dot_product_2 = torch.dot(tensor_1, tensor_2)
dot_product_3 = torch.matmul(tensor_1, tensor_2)

In [ ]:
# Muestra el resultado

#### **1.3.4 Transpuesta**

In [12]:
tensor_1 = torch.tensor([[1, 2, 3]])
# tensor_1

In [14]:
# Transpuesta utilizando el método 1
transpuesta_m1 = tensor_1.T
# transpuesta_m1

In [ ]:
# Transpuesta utilizando el método 2
transpuesta_m2 = torch.transpose(tensor_1, 1, 0)
transpuesta_m2

In [ ]:
tensor_2 = torch.tensor([[1, 2, 3], [5, 5, 5]])
tensor_2

In [ ]:
tran_1 = torch.transpose(tensor_2, 0, 1)
tran_1

In [ ]:
tran_2 = tensor_2.T
tran_2

#### **1.3.5 Red Neuronal**

En PyTorch vienen implementada las redes neuronales artificiales. Para llamarlas debemos utilizar el módulo nn.

In [6]:
import torch.nn as nn

In [10]:
capa = nn.Linear(3, 6)  # 3 entradas → 6 salidas
# capa

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0])
salida = capa(x)

print(salida)

Veamos otro ejemplo con otra red neuronal

In [ ]:
lstm = nn.LSTM(input_size=3, hidden_size=5, batch_first=True)

# (batch, secuencia, características)
x = torch.randn(1, 4, 3)

salida, (h_n, c_n) = lstm(x)

print(salida.shape)  # (1, 4, 5)

In [ ]:
conv = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3)

# (batch, canales, alto, ancho)
x = torch.randn(1, 1, 5, 5)

salida = conv(x)

print(salida.shape)

#### **1.3.6 min, max, mean, sum**

In [15]:
x = torch.arange(0, 100, 10)
# x

In [15]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Obtener el mínimo del tensor
x.min()

In [ ]:
# Obtener el máximo del tensor
x.max()

In [ ]:
# Obtener la media del tensor
x.mean()

In [ ]:
# Obtener la media del tensor
x.type(torch.float32).mean()

In [ ]:
# Obtener la suma
x.sum()

In [ ]:
# Obtener la suma
sum(x)

#### **1.3.7 Positional min/max (Obtener índice del tensor)**

In [18]:
x = torch.arange(10, 110, 10)
# x

In [ ]:
print(f"Tensor: {x}")
print(f"Índice del valor máximo del tensor: {x.argmax()}")
print(f"Índice del valor mínimo del tensor: {x.argmin()}")

#### **1.3.8 Cambiar el tipo de dato**

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

In [ ]:
f16 = tensor.type(torch.float16)
f16.dtype

In [ ]:
tensor_2 = torch.tensor([1, 255, 256, 257])
tensor_2.dtype

In [71]:
tensor_u8 = tensor_2.type(torch.uint8)

### **1.4 Operaciones Avanzadas**

#### **1.4.0 Flatten**

¿Cómo podemos convertir una matriz a un vector?. Supongamos que tenemos un tensor 2D de tamaño (2,3) y esa matriz convertirlo a un vector o tensor 1D.

In [63]:
tensor_1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor_1.shape

torch.Size([2, 3])

Queremos pasar de esto:

[[1, 2, 3],\
 [4, 5, 6]]

 a esto:

[1, 2, 3][4, 5, 6] => [1, 2, 3, 4, 5, 6]

In [65]:
tensor_flat = tensor_1.flatten()
# tensor_flat

In [66]:
tensor_1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [67]:
tensor_flat

tensor([1, 2, 3, 4, 5, 6])

In [16]:
# tensor_flat

In [68]:
tensor_1.view(-1)

tensor([1, 2, 3, 4, 5, 6])

Flatten permite juntar la fila de la matriz con la siguiente fila. ¿Podríamos juntar columnas?, es decir, que ahora el vector nos quede:

[1, 4, 2, 5, 3, 6]

Cuando se llegue a la subsección de permutar se mostrará este ejemplo.

**Importante**: Flatten junta siempre por fila.

#### **1.4.1 Reshape**

Es común tener que cambiar la forma de los tensores, dado que se espera de cierta forma un tensor y se debe convertir a otra dimensión con datos organizados de otra manera. El método `reshape()` cambia la forma (dimensiones) de un tensor sin cambiar sus datos. Si los nuevos tamaños no son compatibles con el número de elementos en el tensor original, lanzará un error.

In [27]:
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
# tensor.shape

La forma o shape de este tensor es (2,3), ahora lo que queremos hacer es convertirlo a esta otra forma (3,2).


Tenemos la siguiente matriz: 

[[1, 2, 3],\
 [4, 5, 6]]

La vamos a convertir a esta otra matriz:

[[1, 2],\
 [3, 4],\
 [5, 6]]

Para realizar lo anterior, debemos utilizar el método reshape() e indicar las dimensiones como parámetro de entrada.

In [31]:
tensor_reshape = tensor.reshape(3, 2)

# print(tensor_reshape)
# print("Shape:", tensor_reshape.shape)

¿Qué ocurre si le indicamos otros valores de dimensiones?


In [30]:
# tensor_reshape_2 = tensor.reshape(3, 3)


**Importante**: Reshape reorganiza automáticamente los valores del tensor a la dimensión indicada, no los modifica. Por otro lado, podemos hacer el equivalente a flatten utilizando reshape pero indicando el valor de -1. Dicho de otro modo: flatten(-1).


#### **1.4.2 Stack**

¿Qué ocurre si tenemos varios tensores y nos gustaría juntarlos en un único tensor?. Con el método stack podemos hacer esa operación de juntar tensores que tienen una forma definida e integrarlos con otros tensores.


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

print("Shape tensor1:", tensor1.shape)
print("Shape tensor2:", tensor2.shape)
print("Shape tensor3:", tensor3.shape)

Si intentamos juntar estos tensores, ocurre algo interesante:

* ¿Cómo sabe PyTorch dónde colocar cada tensor?

* ¿Uno al lado del otro?

* ¿Uno debajo del otro?

Esto se lo hacemos saber a pytorch utilizando dim como parámetro. Por defecto, si no utilizo dim el stack juntará los tensores hacia abajo. Esto es equivalente a decir dim=0.

In [ ]:
tensor_stack = torch.stack([tensor1, tensor2, tensor3])

print(tensor_stack)
print("Shape:", tensor_stack.shape)

¿Si queremos juntar hacia el lado los tensores?, ¿Qué debemos hacer?.

In [ ]:
tensor_stack = torch.stack([tensor1, tensor2, tensor3], dim=1)

print(tensor_stack)
print("Shape:", tensor_stack.shape)

¿Qué ocurre si tenemos matrices?

In [ ]:
matriz_1 = torch.tensor([
        [1,2,3],
        [4,5,6],
        [7,8,9],
])

matriz_2 = matriz_1
matriz_3 = matriz_1

matriz_1

In [ ]:
tensor_stack = torch.stack([matriz_1, matriz_2, matriz_3], dim=0)

print(tensor_stack)
print("Shape:", tensor_stack.shape)

Podemos apreciar que se agrega una nueva dimensión, pero ¿Qué pasa si no quiero crear una nueva dimensión, sino simplemente pegar tensores o concatenar?

#### **1.4.3 Cat (Concatenación)**

Cat a diferencia de stack, no agrega una nueva dimensión, simplemente utiliza las que ya existen.

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Shape de a:", a.shape)
print("Shape de b:", b.shape)

In [ ]:
c = torch.cat([a, b])

print(c)
print("Shape:", c.shape)

¿Cómo hubiese pasado si utilizamos stack?

In [61]:
d = torch.stack([a,b])

# d

¿Podemos elegir la dirección de concatenación?

* dim = 0 (Concatena hacia al lado con tensores 1D o vectores)

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = torch.cat([a, b], dim=0)

print(c)
print("Shape:", c.shape)

Cuando tenemos matrices ocurre lo siguiente:

* dim = 0 (Concatena hacia abajo)
* dim = 1 (Concatena hacia al lado)

In [ ]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

cat_down = torch.cat([A, B], dim=0)

print(cat_down)
print("Shape:", cat_down.shape)

In [ ]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

cat_down = torch.cat([A, B], dim=1)

print(cat_down)
print("Shape:", cat_down.shape)

#### **1.4.4 Squeeze**

Elimina las dimensiones de tamaño 1 de un tensor. Por ejemplo, si tienes un tensor de forma ``(1, 3, 1, 5)``, usar ``squeeze()`` eliminará las dimensiones que tienen un tamaño de 1, quedando un tensor de forma ``(3, 5)``.

In [ ]:
torch.manual_seed(5)

random_tensor = torch.rand(size=(1,3), dtype=torch.bfloat16)

print("Vemos la dimensión del tensor:", random_tensor.ndim)
print("Vemos la forma del tensor:", random_tensor.shape)

In [18]:
# random_tensor

In [19]:
# random_tensor.squeeze()

In [70]:
nuevo_vector = random_tensor.squeeze()

In [20]:
# nuevo_vector.ndim

In [ ]:
y_stacked = torch.stack([random_tensor, random_tensor, random_tensor], dim=1)

# print("Vemos la dimensión del tensor:", y_stacked.ndim)
# print("Vemos la forma del tensor:", y_stacked.shape)

In [22]:
# y_stacked

In [23]:
# y_stacked.ndim

Podemos apreciar que se agregó una dimensión extra, también conocida como la dimensión del batch. ¿Podemos eliminar esa dimensión?, la respuesta es sí, podemos eliminar la dimensión del batch.

In [55]:
y_stacked_squeeze = y_stacked.squeeze()

In [24]:
# Muestra cómo quedó el tensor y visualiza la forma
# y_stacked_squeeze.ndim

Si podemos eliminar una dimensión, ¿Podemos volver agregar la dimensión?

In [60]:
y_stacked_unsqueeze = y_stacked_squeeze.unsqueeze(dim=0)

In [25]:
# Muestra el resultado y juega utilizando dim=1, dim=2
# y_stacked_unsqueeze.ndim

#### **1.4.5 Unsqueeze**

Agrega una nueva dimensión de tamaño 1 en una posición específica del tensor. Esto es útil cuando necesitas expandir un tensor para que encaje en una operación que requiere una forma específica.

In [72]:
# creamos un tensor aleatorio
x = torch.randn(3,5)

In [ ]:
# Verifique la forma

In [26]:
# x.shape

In [74]:
x_unsqueezed = x.unsqueeze(0)  # Añade una nueva dimensión en el eje 0

In [76]:
# Verifique la forma

#### **1.4.6 Permutar**

El método `permute()` reorganiza las dimensiones de un tensor. Este método permite cambiar el orden de las dimensiones del tensor, especificando una nueva secuencia de índices. Por ejemplo, puede ocurrir que cargas una imagen con numpy y la forma de la imagen a color es (ancho, alto, canal) -> RGB. En PyTorch, se trata distinto esto, se espera una imagen de la forma (canal, ancho, alto).

¿Cómo podemos cambiar el orden de dimensiones?

Dentro del método `permute()` podemos indicarle los índices que queremos intercambiar, por ejemplo:

Tenemos un tensor de 3D de la forma (2,3,4), sus dimensiones son las siguientes:

Dimensión 0 → tamaño 2\
Dimensión 1 → tamaño 3\
Dimensión 2 → tamaño 4

Entonces, al método permite le indicamos qué índices queremos intercambiar del tensor.

In [ ]:
x_original = torch.rand(size=(64, 28, 28)) 

# Permutar nos permite mover los ejes
x_permuted = x_original.permute(2, 0, 1) # Aquí estamos diciendo que el índice de la dimensión 2 (28), lo queremos en la primera posición, el índice de la primera dimensión (64) en la segunda posición y el índice de la segunda dimensión (28) lo queremos en la última dimensión del nuevo tensor

print(f"Shape del tensor original: {x_original.shape}")
print(f"Shape del tensor permutado: {x_permuted.shape}")

**¿Te acuerdas del ejemplo que hicimos con flatten donde teníamos una matriz?**

In [ ]:
tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor.shape

In [ ]:
tensor_flat = tensor.flatten()
# tensor_flat

Ahora vamos a invertir las dimensiones para obtener una matriz donde la columna de la matriz original para a ser la fila de la nueva matriz.

In [ ]:
tensor_permutado = tensor.permute(1, 0)
tensor_permutado

In [ ]:
tensor_flat_2 = tensor_permutado.flatten()
tensor_flat_2

### **1.5 Indexing**

Esta sección será más práctica, dado que se tendrá que manipular cada tensor utilizando el slicing.

#### **1.5.1 Indexing a Tensores 2D**

In [69]:
# Crea un tensor aleatorio de tamaño 6x4 y utiliza una semilla de valor 5
torch.manual_seed(5)

random_tensor = torch.rand(size=(6,4))
random_tensor

tensor([[0.8303, 0.1261, 0.9075, 0.8199],
        [0.9201, 0.1166, 0.1644, 0.7379],
        [0.0333, 0.9942, 0.6064, 0.5646],
        [0.0724, 0.6593, 0.7150, 0.5793],
        [0.9809, 0.6502, 0.0566, 0.9201],
        [0.6698, 0.2615, 0.0407, 0.7850]])

In [ ]:
# Muestra su forma y dimensión
random_tensor.shape, random_tensor.ndim

In [ ]:
# Muestra la primera fila
random_tensor[0]

In [82]:
# Muestra la última fila
random_tensor[-1]

tensor([0.6698, 0.2615, 0.0407, 0.7850])

In [83]:
# Muestra la primera columna, recuerda que los : indica que selecciono todos los elementos de la fila
random_tensor[:, 0]

tensor([0.8303, 0.9201, 0.0333, 0.0724, 0.9809, 0.6698])

In [ ]:
# Muestra la última columna, recuerda que los : indica que selecciono todos los elementos de la fila
random_tensor[:, -1]

In [84]:
# Muestra las 3 primeras filas, recuerda que puedes no indicar el índice de inicio, ya que por detrás se utiliza automáticamente
random_tensor[:3]

tensor([[0.8303, 0.1261, 0.9075, 0.8199],
        [0.9201, 0.1166, 0.1644, 0.7379],
        [0.0333, 0.9942, 0.6064, 0.5646]])

In [85]:
# Muestra las 2 últimas columnas
random_tensor[:, 2:]

tensor([[0.9075, 0.8199],
        [0.1644, 0.7379],
        [0.6064, 0.5646],
        [0.7150, 0.5793],
        [0.0566, 0.9201],
        [0.0407, 0.7850]])

In [ ]:
# Crea una matriz de ceros de tamaño 3x5 

In [ ]:
# Convierte toda la primera fila en unos

In [ ]:
# Convierte toda la última columna en números 5 fila en unos


#### **1.5.2 Slicing a Tensores 3D**

In [16]:
import torch

In [18]:
torch.manual_seed(5)
random_tensor = torch.rand(size=(3,5,6))

In [ ]:
# Muestra el tensor que creamos, donde es una secuencia de 3 matrices de tamaño 5x6

In [20]:
# Podemos seleccionar el último batch
random_tensor[-1]

tensor([[0.2225, 0.2148, 0.3662, 0.3384, 0.1600, 0.9041],
        [0.5557, 0.7280, 0.8709, 0.1760, 0.8817, 0.2495],
        [0.4204, 0.8784, 0.9610, 0.9389, 0.7876, 0.9647],
        [0.3198, 0.4682, 0.3290, 0.4633, 0.4392, 0.7671],
        [0.8437, 0.1399, 0.2239, 0.3462, 0.5668, 0.3059]])

In [ ]:
# Podemos verificar esto viendo su forma
random_tensor[-1].shape

torch.Size([5, 6])

In [ ]:
# Del último batch convierte la primera fila y columna en unos, y convierte la última fila y columna en unos. Nota:
# Existen dos formas de realizar esto con la notación del corchete

In [ ]:
# Ahora los valores encerrados dentro de los valores que son unos, conviértelos en cero

### **1.6 PyTorch y NumPy**

#### **1.6.1 NumPy a PyTorch**

In [86]:
import numpy as np
import torch

In [87]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### **1.6.2 PyTorch a NumPy**

In [45]:
tensor = torch.arange(0,9)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
array = tensor.numpy()
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## **2. Ejercicios**

1. Crea un tensor de 3x3 de números aleatorios.
2. Crea un tensor de 5x5 de ceros.
3. Crea un tensor de 4x4 de unos.
4. Crea un tensor de 2x3 de números enteros (por ejemplo, usando torch.randint).
5. Suma y resta dos tensores de igual forma.
6. Multiplica y divide dos tensores de igual forma.
7. Aplica la función ``torch.abs()`` a un tensor con valores negativos.
8. Crea un tensor de forma (2, 3, 4), luego aplícale:
    * ``reshape()`` para cambiar su forma a (6, 4).
    * ``squeeze()`` para eliminar dimensiones de tamaño 1.
    * ``unsqueeze()`` para agregar una nueva dimensión en la posición 0.
    * ``view()`` para cambiar la forma a (3, 8).
9. Crea dos tensores x y y de forma (3, 4).
    * Usa torch.cat() para concatenarlos a lo largo de la dimensión 0 y la dimensión 1.
    * Usa torch.stack() para apilarlos a lo largo de una nueva dimensión.
10. Crea un tensor de forma (3, 2) y usa torch.transpose() o .T para transponerlo.
11. Crea un tensor de forma (2, 3, 4) y usa torch.permute() para reorganizar las dimensiones a (4, 2, 3).
12. Crea un tensor de forma (2, 3, 4) y usa view() para aplanarlo a un tensor de forma (24,).

## **3. Referencias**

A continuación te dejo una página donde puedes obtener más información.

1. [Aprender Pytorch](https://www.learnpytorch.io/00_pytorch_fundamentals/#00-pytorch-fundamentals)